<a href="https://colab.research.google.com/github/marinvirdol/learnpytorchio/blob/main/00_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 00. PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


## Introduction to Tensors

Anytime you encode data into number is of tensor data type.

Their job is to represent data in a numerical way.

### Creating Tensors

PyTorch tensors are created using `torch.Tensor()`-> https://docs.pytorch.org/docs/stable/tensors.html

In [2]:
# scalar -> has only magnitude (size) -> 0 dimensions
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim # check the dimension of the tensor

0

In [4]:
# get tensor back as python int
scalar.item()

7

In [5]:
# vector -> has magnitude (size) and drection -> 1 dimension
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX -> 2 dimensions
MATRIX = torch.tensor([[7,8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR -> any amount of dimensions
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
# the dimensions go outer to inner
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors
When building machine learning models with PyTorch, it's rare to create tensors by hand.

Why random tensors?

They are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`


In [16]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1391, 0.0627, 0.9469, 0.1431],
        [0.5898, 0.6755, 0.2008, 0.8062],
        [0.2948, 0.2094, 0.7356, 0.1234]])

In [17]:
random_tensor.ndim

2

In [18]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [19]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
# the default type (unless you explicitly define what the data type is, default is float32)
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [22]:
# use torch.range() -> deprecated
torch.range(0, 10)

/tmp/ipython-input-2439239933.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [23]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
torch.arange(start=1, end=1000, step=77)

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [25]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
# creating tensors-like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
The default is float32.

Tensot datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning.
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [27]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # define what data type the tensor is
                               device=None, # default CPU can be also CUDA. What device is your tensor on?
                               requires_grad=False) # whether or not to track gradients with this tensors operations

float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
# convert tensor data type
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_16_tensor * float_32_tensor # no error

tensor([ 9., 36., 81.])

In [31]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [32]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors
1. datatype -> `tensor.dtype`
2. shape -> `tensor.shape`
3. device -> `tensor.device`

In [33]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8704, 0.1857, 0.4291, 0.9950],
        [0.3753, 0.6268, 0.0227, 0.4978],
        [0.4592, 0.7828, 0.2909, 0.9610]])

In [34]:
# find out details about tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape} {some_tensor.size()}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.8704, 0.1857, 0.4291, 0.9950],
        [0.3753, 0.6268, 0.0227, 0.4978],
        [0.4592, 0.7828, 0.2909, 0.9610]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4]) torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* additioin
* substraction
* multiplication (element-wise)
* division
* matrix multiplication

In [35]:
# create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [36]:
# multiply tensor by 10
tensor = tensor * 10

In [37]:
tensor

tensor([10, 20, 30])

In [38]:
# substract 10
tensor - 10

tensor([ 0, 10, 20])

In [39]:
# try out pytorch in-built functions
mult_tensor = torch.mul(tensor, 10)
print(mult_tensor)
print(tensor)

tensor([100, 200, 300])
tensor([10, 20, 30])


### matrix multiplication
Two main ways:
1. element ways
2. matrix multiplication (dot product) -> the most common tensor operation we'll find inside neural networks

More info on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resuling matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [40]:
# element wise multiplication
tensor = torch.tensor([1, 2, 3])
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [41]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [42]:
# matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [43]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 1.68 ms, sys: 0 ns, total: 1.68 ms
Wall time: 2.42 ms


In [44]:
%%time
torch.matmul(tensor, tensor) # uses vectorization to achieve this performance

CPU times: user 497 µs, sys: 0 ns, total: 497 µs
Wall time: 380 µs


tensor(14)

### One of the most common errors in deep learning: **shape errors**

In [45]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [46]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [47]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [48]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [49]:
# the matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)


In [50]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [51]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [52]:
# find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [53]:
# the torch.mean() requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [54]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [55]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
# find the position in tensor that has the minimum value -> returns index position of target tensor where the minimum value occurs
x.argmin(), x[0]

(tensor(0), tensor(0))

In [57]:
y = torch.arange(1, 100, 10)
y.argmin(), y[0]

(tensor(0), tensor(1))

In [58]:
# find the position in tensor that has the maximum value -> return index position of target tensor where the maximum value occurs
y.argmax()

tensor(9)

In [59]:
y[9]

tensor(91)

### Reshaping, stacking, squeezing and unsqueezing

* **Reshape** - reshapes an input tensor to a defined shape
* **View** - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* **Stacking** - combine multiple tensors on top of each other.
* **Squeeze** - removes all `1` dimensions from a tensor
* **Unsqueeze** - add a `1` dimension to a target tensor
* **Permute** - return a view off the input tensor with dimensions permuted(swapped) in a certain way

*The main point of all of these is to manpulate our tensors in some way to change their shape or dimensions.*

In [60]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [61]:
# add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [62]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [63]:
# changing z, changes x -> the vieww of a tensor shares the same memory as the original input
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [64]:
# stack tensors on top of each other

In [65]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [66]:
# squeeze remove all single dimensions from a target tensor
x_reshaped.shape

torch.Size([1, 9])

In [67]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [68]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [69]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add an extra dimension
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shappe: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shappe: torch.Size([1, 9])


In [70]:
x_unsqueezed.unsqueeze(dim=0)

tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [71]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(224, 224, 3) # [height, width, color_channels]

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)
print(f"previous shape: {x_original.shape}")
print(f"new shape: {x_permuted.shape}") # [color_channels, height, width]


previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [1]:
# create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
y = torch.arange(1, 10)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [2]:
# let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [78]:
# let's index on the middle bracket (dim=1)
x[0][0], x[0, 0] # these two give back the same result

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [82]:
# let's index on the most inner bracket (last dimension)
x[0][0][0], x[0][0][1], x[0][1][1]

(tensor(1), tensor(2), tensor(5))

In [4]:
# get all values of the 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [5]:
# get all values of the 0th dimension and the index 1 of the 1st dimension
x[:, 1]

tensor([[4, 5, 6]])

In [87]:
# get all values of the 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [9]:
# get all values of the 0th dimentsion but only the 1 index of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [10]:
# get index 0 of the 0th and 1st dimension and all the values of the 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [11]:
# index on x to return 9
x[0, 2, 2]

tensor(9)

In [15]:
# index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

### PyTorch Tensors & NumPy

Quite often we'll start off with our data in NumPy because it's numerical data. Because of this, PyTorch has functionality to interact with it nicely.

The two main methods are:
* Data in NumPy array that we want as a PyTorch tensor - `torch.from_numpy(ndarray)`
* PyTorch tensor to NumPy - `torch.tensor.numpy()`

In [22]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # when converting from numpy to tensor, the tensor reflects numpy's arrat datatype unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [19]:
array.dtype # by default NumPy arrays are created with float64 and if we convert it to a tensor, it will keep the same datatype

dtype('float64')

In [21]:
# torch default datatype is float32
torch.arange(1.0, 8.0).dtype

torch.float32

In [24]:
# convert NumPy array float64 to PyTorch tensor (float64) to PyTorch tensor (float32)
torch.from_numpy(array).type(torch.float32).dtype

torch.float32

In [25]:
# if we change the values in the NumPy array, what will that do to the converted tensor?
array = array + 1
array, tensor # it doesn't change the value of the tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [26]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [27]:
numpy_tensor.dtype

dtype('float32')

In [28]:
# change the tensor, what happens to the numpy array created from that tensor?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take the random out of random)

So far, we've discussed that neural networks start with random numbers to describe patterns in data (poor representations of data) and try to improve those random numbers using tensor operations (and a few other things we haven't discussed yet) to better describe patterns in data.

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again -> ...`

Although randomness is nice and powerful, sometimes you'd like there to be a little less randomness.

Why?
* verifying research and experimental results under the same conditions
* debugging model training behaviour by eliminating randomness as a factor
* fairly comparing different models or configurations when benchmarking

**Reproducibility** refers to ensuring that running the same code multiple times yields the same results - an essential aspect for debugging, model comparison, and scientific reliability.

**Source of randomness in PyTorch**
* random weight initialization when building models
* data shuffling or random sampling in DataLoader
* Non-deterministic operations on GPU due to parallelism
* Different hardware, threads or library versions

In [1]:
import torch

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"tensor A: \n{random_tensor_A}\n")
print(f"tensor B: \n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")

random_tensor_A == random_tensor_B

tensor A: 
tensor([[0.2225, 0.3008, 0.8820, 0.1707],
        [0.4371, 0.9630, 0.5862, 0.7758],
        [0.5891, 0.1853, 0.3383, 0.9557]])

tensor B: 
tensor([[0.1248, 0.2886, 0.9276, 0.0348],
        [0.2862, 0.7487, 0.8150, 0.8969],
        [0.4825, 0.3399, 0.2575, 0.7255]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Just as expected, the two tensors come out with different values.

But what if we wanted to create two random tensors with the same values?

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially, what random seed does is flavour the randomness. As in, the tensors would still contain random values but they would be of the same flavour.

In [2]:
# let's create some random but reproducible tensors
RANDOM_SEED = 42 # whatever value you want
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)
random_tensor_D = torch.rand(3, 4)

random_tensor_C == random_tensor_D

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [3]:
torch.manual_seed(RANDOM_SEED)
random_tensor_E = torch.rand(3, 4)

# have to reset the seed every time a new .rand() is called
# without this tensor F would be different from tensor E
torch.manual_seed(RANDOM_SEED)
random_tensor_F = torch.rand(3, 4)

random_tensor_E == random_tensor_F

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Running tensors on GPUs (for faster computations)

Deep learning algorithms require a lot of numerical operations andd by default these are done on a CPU.

The GPU is often much faster at performing the specific types of operations neural networks need (matrix multiplications) than CPUs.

GPUs = faster computation on numbers, thanks to CUD + NVIDIA hardware.

You should look to use one whenever you are training a neural network because it will probably speed up the training time dramatically.



In [1]:
!nvidia-smi

Sat Oct 25 11:59:01 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off |   00000000:00:04.0 Off |                    0 |
| N/A   32C    P0             45W /  400W |       0MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+-----

In [2]:
# check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running cmpute on the GPU or CPU, it's best practice to setup device agnostic code: https://docs.pytorch.org/docs/main/notes/cuda.html#device-agnostic-code

In [4]:
# setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [5]:
# count number of device
torch.cuda.device_count()

1


Knowing the number of GPUs PyTorch has access to is helpful incase you wanted to run a specific process on one GPU and another process on another (PyTorch also has features to let you run a process across all GPUs).

Or, if you want to do faster computing you can use a GPU but if you want to do much faster computing, you can use multiple GPUs.

### Putting tensors (and models) on the GPU


In [8]:
# create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [9]:
# move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to CPU

In [10]:
# if tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [11]:
# to fix the GPU tensor with NumPy issue, we set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])