<a href="https://colab.research.google.com/github/marinvirdol/learnpytorchio/blob/main/00_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 00. PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


## Introduction to Tensors

Anytime you encode data into number is of tensor data type.

Their job is to represent data in a numerical way.

### Creating Tensors

PyTorch tensors are created using `torch.Tensor()`-> https://docs.pytorch.org/docs/stable/tensors.html

In [2]:
# scalar -> has only magnitude (size) -> 0 dimensions
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim # check the dimension of the tensor

0

In [4]:
# get tensor back as python int
scalar.item()

7

In [5]:
# vector -> has magnitude (size) and drection -> 1 dimension
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX -> 2 dimensions
MATRIX = torch.tensor([[7,8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR -> any amount of dimensions
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
# the dimensions go outer to inner
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors
When building machine learning models with PyTorch, it's rare to create tensors by hand.

Why random tensors?

They are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`


In [16]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5472, 0.9456, 0.2229, 0.1590],
        [0.7355, 0.9190, 0.6252, 0.9223],
        [0.5787, 0.3442, 0.5793, 0.0137]])

In [17]:
random_tensor.ndim

2

In [18]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [19]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
# the default type (unless you explicitly define what the data type is, default is float32)
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [22]:
# use torch.range() -> deprecated
torch.range(0, 10)

/tmp/ipython-input-2439239933.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [23]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
torch.arange(start=1, end=1000, step=77)

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [25]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
# creating tensors-like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
The default is float32.

Tensot datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning.
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [27]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # define what data type the tensor is
                               device=None, # default CPU can be also CUDA. What device is your tensor on?
                               requires_grad=False) # whether or not to track gradients with this tensors operations

float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
# convert tensor data type
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_16_tensor * float_32_tensor # no error

tensor([ 9., 36., 81.])

In [31]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [32]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors
1. datatype -> `tensor.dtype`
2. shape -> `tensor.shape`
3. device -> `tensor.device`

In [33]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1350, 0.7459, 0.6094, 0.2459],
        [0.0728, 0.8799, 0.0906, 0.3363],
        [0.0084, 0.2760, 0.3269, 0.8073]])

In [34]:
# find out details about tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape} {some_tensor.size()}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.1350, 0.7459, 0.6094, 0.2459],
        [0.0728, 0.8799, 0.0906, 0.3363],
        [0.0084, 0.2760, 0.3269, 0.8073]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4]) torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* additioin
* substraction
* multiplication (element-wise)
* division
* matrix multiplication

In [35]:
# create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [36]:
# multiply tensor by 10
tensor = tensor * 10

In [37]:
tensor

tensor([10, 20, 30])

In [38]:
# substract 10
tensor - 10

tensor([ 0, 10, 20])

In [39]:
# try out pytorch in-built functions
mult_tensor = torch.mul(tensor, 10)
print(mult_tensor)
print(tensor)

tensor([100, 200, 300])
tensor([10, 20, 30])


### matrix multiplication
Two main ways:
1. element ways
2. matrix multiplication (dot product) -> the most common tensor operation we'll find inside neural networks

More info on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resuling matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [40]:
# element wise multiplication
tensor = torch.tensor([1, 2, 3])
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [41]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [42]:
# matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [43]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 1.42 ms, sys: 60 µs, total: 1.48 ms
Wall time: 2.62 ms


In [44]:
%%time
torch.matmul(tensor, tensor) # uses vectorization to achieve this performance

CPU times: user 379 µs, sys: 57 µs, total: 436 µs
Wall time: 355 µs


tensor(14)

### One of the most common errors in deep learning: **shape errors**

In [45]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [46]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [47]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [48]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [49]:
# the matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)


In [64]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [51]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [52]:
# find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [54]:
# the torch.mean() requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [55]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [69]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [70]:
# find the position in tensor that has the minimum value -> returns index position of target tensor where the minimum value occurs
x.argmin(), x[0]

(tensor(0), tensor(0))

In [71]:
y = torch.arange(1, 100, 10)
y.argmin(), y[0]

(tensor(0), tensor(1))

In [72]:
# find the position in tensor that has the maximum value -> return index position of target tensor where the maximum value occurs
y.argmax()

tensor(9)

In [73]:
y[9]

tensor(91)