<a href="https://colab.research.google.com/github/marinvirdol/learnpytorchio/blob/main/00_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 00. PyTorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


## Introduction to Tensors

Anytime you encode data into number is of tensor data type.

Their job is to represent data in a numerical way.

### Creating Tensors

PyTorch tensors are created using `torch.Tensor()`-> https://docs.pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar -> has only magnitude (size) -> 0 dimensions
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim # check the dimension of the tensor

0

In [ ]:
# get tensor back as python int
scalar.item()

7

In [ ]:
# vector -> has magnitude (size) and drection -> 1 dimension
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX -> 2 dimensions
MATRIX = torch.tensor([[7,8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR -> any amount of dimensions
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
# the dimensions go outer to inner
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors
When building machine learning models with PyTorch, it's rare to create tensors by hand.

Why random tensors?

They are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`


In [ ]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8217, 0.4000, 0.4639, 0.8687],
        [0.7800, 0.2034, 0.4308, 0.2871],
        [0.9835, 0.9579, 0.6930, 0.1258]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [3]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
# create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
# the default type (unless you explicitly define what the data type is, default is float32)
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [9]:
# use torch.range() -> deprecated
torch.range(0, 10)

/tmp/ipython-input-4106555132.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
torch.arange(1, 10)

In [11]:
torch.arange(start=1, end=1000, step=77)

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [16]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
# creating tensors-like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
The default is float32.

Tensot datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning.
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [21]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # define what data type the tensor is
                               device=None, # default CPU can be also CUDA. What device is your tensor on?
                               requires_grad=False) # whether or not to track gradients with this tensors operations

float_32_tensor

tensor([3., 6., 9.])

In [19]:
float_32_tensor.dtype

torch.float32

In [24]:
# convert tensor data type
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_16_tensor * float_32_tensor # no error

tensor([ 9., 36., 81.])

In [26]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [27]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### getting information from tensors
1. datatype -> `tensor.dtype`
2. shape -> `tensor.shape`
3. device -> `tensor.device`

In [29]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2861, 0.7800, 0.2797, 0.0536],
        [0.8011, 0.3659, 0.1671, 0.6738],
        [0.5667, 0.5034, 0.9245, 0.7681]])

In [32]:
# find out details about tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape} {some_tensor.size()}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.2861, 0.7800, 0.2797, 0.0536],
        [0.8011, 0.3659, 0.1671, 0.6738],
        [0.5667, 0.5034, 0.9245, 0.7681]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4]) torch.Size([3, 4])
Device of tensor: cpu
